import type {InterfaceLanguage} from './languages';
// Each row is complete in zh, en, ja, fr, es and ru. No implicit language fallback.
export const PANEL_COPY = {
  close:['關閉','Close','閉じる','Fermer','Cerrar','Закрыть'],
  back:['返回文件清單','Back to documents','資料一覧に戻る','Retour aux documents','Volver a documentos','К списку документов'],
  loading:['載入中……','Loading…','読み込み中…','Chargement…','Cargando…','Загрузка…'],
  busy:['處理中……','Working…','処理中…','Traitement…','Procesando…','Обработка…'],
  cancel:['取消','Cancel','キャンセル','Annuler','Cancelar','Отмена'],
  retry:['重試','Retry','再試行','Réessayer','Reintentar','Повторить'],
  details:['詳細資訊','Details','詳細','Détails','Detalles','Подробности'],
  tools:['工具','Tools','ツール','Outils','Herramientas','Инструменты'],
  tasks:['我的產出','My outputs','作成した資料','Mes productions','Mis resultados','Мои результаты'],
  mcp:['連接 AI 工具（MCP）','Connect AI tools (MCP)','AI ツールに接続（MCP）','Connecter des outils IA (MCP)','Conectar herramientas IA (MCP)','Подключить ИИ-инструменты (MCP)'],
  error:['無法完成操作，請稍後重試。','Could not complete the request. Please try again.','処理できませんでした。再試行してください。','Impossible de terminer. Veuillez réessayer.','No se pudo completar. Inténtelo de nuevo.','Не удалось выполнить запрос. Повторите попытку.'],
  expired:['登入已逾時，請重新整理並登入。','Your session expired. Refresh and sign in.','セッションが切れました。再読み込みしてログインしてください。','Session expirée. Actualisez et reconnectez-vous.','La sesión caducó. Actualice e inicie sesión.','Сеанс истёк. Обновите страницу и войдите.'],
  denied:['你沒有執行此操作的權限。','You do not have permission for this action.','この操作の権限がありません。','Vous n’avez pas l’autorisation nécessaire.','No tiene permiso para esta acción.','У вас нет разрешения на это действие.'],
  conflict:['內容已更新，請重新載入並檢查。','The content changed. Reload and review it.','内容が更新されました。再読み込みして確認してください。','Le contenu a changé. Rechargez et vérifiez.','El contenido cambió. Recárguelo y revíselo.','Содержимое изменилось. Обновите и проверьте его.'],
  missing:['找不到資料，或資料已到期。','This item is unavailable or has expired.','項目が見つからないか、期限が切れています。','Élément introuvable ou expiré.','El elemento no existe o ha caducado.','Элемент не найден или срок хранения истёк.'],
  tooLarge:['選取內容超過處理上限。','The selected content exceeds the processing limit.','選択した内容が処理上限を超えています。','Le contenu dépasse la limite de traitement.','El contenido supera el límite de procesamiento.','Содержимое превышает допустимый объём.'],
  invalid:['請檢查輸入內容或來源擷取狀態。','Check the input and source extraction status.','入力内容と原文の抽出状態を確認してください。','Vérifiez la saisie et l’extraction des sources.','Revise los datos y la extracción de las fuentes.','Проверьте ввод и состояние извлечения источников.'],
  rateLimit:['已達每小時工作上限，請稍後再試。','Hourly task limit reached. Try again later.','1 時間のタスク上限に達しました。後でもう一度お試しください。','Limite horaire atteinte. Réessayez plus tard.','Se alcanzó el límite por hora. Inténtelo más tarde.','Достигнут часовой лимит задач. Повторите позже.'],
  unavailable:['服務暫時無法使用，請稍後重試。','The service is temporarily unavailable.','サービスを一時的に利用できません。','Le service est temporairement indisponible.','El servicio no está disponible temporalmente.','Сервис временно недоступен.'],
  chart:['圖表','Chart','図表','Graphique','Gráfico','Диаграмма'],
  pdf:['PDF 報告','PDF report','PDF レポート','Rapport PDF','Informe PDF','Отчёт PDF'],
  pptx:['投影片','Slides','スライド','Présentation','Presentación','Презентация'],
  translation:['段落翻譯','Passage translation','段落の翻訳','Traduction de passages','Traducción de pasajes','Перевод фрагментов'],
  index:['切片發布','Chunk publication','チャンクの公開','Publication des segments','Publicación de fragmentos','Публикация фрагментов'],
  createPdf:['產出 PDF','Create PDF','PDF を作成','Créer un PDF','Crear PDF','Создать PDF'],
  createSlides:['產出投影片','Create slides','スライドを作成','Créer une présentation','Crear presentación','Создать слайды'],
  slideDeckPlan:['共 {count} 頁，引用附於各頁，詳細說明保留在講者備註。','{count} slides, with citations on each slide and detail in speaker notes.','全 {count} 枚。各スライドに出典、発表者ノートに詳細を記載します。','{count} diapositives, avec sources sur chaque page et détails dans les notes.','{count} diapositivas, con fuentes en cada página y detalles en las notas.','{count} слайдов: ссылки на каждом, подробности в заметках.'],
  slideReviewIntro:['逐頁檢查重點、證據與版型。可修改內容及順序；過長或不符合引用的內容需先修正才能產出。','Review each slide’s message, evidence and layout. Edit content and order; oversized text or invalid citations must be corrected before export.','各スライドの要点、根拠、レイアウトを確認してください。内容と順序を編集できます。長すぎる文章や不正な引用は出力前に修正してください。','Vérifiez le message, les sources et la disposition. Modifiez le contenu et l’ordre ; corrigez les textes trop longs ou citations invalides avant export.','Revise mensaje, fuentes y diseño. Edite contenido y orden; corrija textos extensos o citas inválidas antes de exportar.','Проверьте смысл, источники и макет. Измените содержание и порядок; исправьте слишком длинный текст и неверные ссылки до экспорта.'],
  slideTextTooLong:['部分文字超出版面可讀範圍。請縮短標題、重點或表格文字，將補充說明移至講者備註。','Some text exceeds the readable layout. Shorten titles, points or table cells and move supporting detail to speaker notes.','一部の文章がレイアウトに収まりません。見出し、要点、表を短くし、詳細は発表者ノートへ移してください。','Certains textes dépassent la mise en page lisible. Raccourcissez titres, points ou cellules et placez les détails dans les notes.','Algunos textos no caben de forma legible. Acorte títulos, puntos o celdas y pase los detalles a las notas.','Часть текста не помещается. Сократите заголовки, пункты или ячейки и перенесите подробности в заметки.'],
  audienceGoal:['希望聽眾理解什麼','What should the audience understand?','聞き手に伝えること','Ce que le public doit comprendre','Qué debe comprender el público','Что должна понять аудитория'],
  slideNumber:['第 {number} 頁','Slide {number}','スライド {number}','Diapositive {number}','Diapositiva {number}','Слайд {number}'],
  slideTitle:['本頁標題','Slide title','スライドの題名','Titre de la diapositive','Título de la diapositiva','Заголовок слайда'],
  takeaway:['本頁要點','Main takeaway','要点','Message principal','Idea principal','Главная мысль'],
  claimType:['內容性質','Type of claim','内容の区分','Nature du propos','Tipo de afirmación','Тип утверждения'],
  claim_evidence:['資料依據','Evidence','根拠','Constats','Evidencia','Данные'],
  claim_inference:['推論','Inference','推論','Interprétation','Inferencia','Вывод'],
  claim_recommendation:['建議','Recommendation','提案','Recommandation','Recomendación','Рекомендация'],
  layout_briefing:['重點說明','Briefing','要点説明','Synthèse','Síntesis','Основные положения'],
  layout_comparison:['比較表','Comparison','比較表','Comparaison','Comparación','Сравнение'],
  layout_process:['流程','Process','手順','Processus','Proceso','Процесс'],
  layout_evidence:['引文分析','Source analysis','引用の分析','Analyse de source','Análisis de fuente','Анализ источника'],
  layout_chart:['數據圖表','Data chart','データ図表','Graphique de données','Gráfico de datos','Диаграмма данных'],
  sourceQuote:['原文引句','Original quotation','原文の引用','Citation originale','Cita original','Исходная цитата'],
  speakerNotes:['講者備註','Speaker notes','発表者ノート','Notes de présentation','Notas del presentador','Заметки докладчика'],
  pointLabel:['重點 {number} 的標題','Point {number} label','項目 {number} の見出し','Titre du point {number}','Título del punto {number}','Заголовок пункта {number}'],
  pointDetail:['重點 {number} 的說明','Point {number} explanation','項目 {number} の説明','Explication du point {number}','Explicación del punto {number}','Пояснение пункта {number}'],
  columnNumber:['第 {number} 欄標題','Column {number} heading','列 {number} の見出し','En-tête de colonne {number}','Encabezado de columna {number}','Заголовок столбца {number}'],
  tableCell:['第 {row} 列第 {column} 欄','Row {row}, column {column}','行 {row}、列 {column}','Ligne {row}, colonne {column}','Fila {row}, columna {column}','Строка {row}, столбец {column}'],
  moveSlideUp:['將第 {number} 頁往前移','Move slide {number} earlier','スライド {number} を前へ','Avancer la diapositive {number}','Adelantar diapositiva {number}','Переместить слайд {number} раньше'],
  moveSlideDown:['將第 {number} 頁往後移','Move slide {number} later','スライド {number} を後へ','Reculer la diapositive {number}','Retrasar diapositiva {number}','Переместить слайд {number} позже'],
  slidesCreate:['另存 Google Slides','Save to Google Slides','Google スライドに保存','Enregistrer dans Google Slides','Guardar en Google Slides','Сохранить в Google Презентациях'],
  slidesOpen:['在 Google Slides 開啟','Open in Google Slides','Google スライドで開く','Ouvrir dans Google Slides','Abrir en Google Slides','Открыть в Google Презентациях'],
  slidesCreating:['正在儲存至 Google Slides……','Saving to Google Slides…','Google スライドに保存中…','Enregistrement dans Google Slides…','Guardando en Google Slides…','Сохранение в Google Презентациях…'],
  slidesIntro:['建立可編輯的 Google 簡報，存入你的 Drive。首次使用需授權本應用建立或由你選取的檔案。','Create an editable presentation in your Drive. On first use, authorize access to files this app creates or you select.','編集可能なプレゼンテーションを自分の Drive に保存します。初回は、このアプリが作成したファイルまたは自分で選択したファイルへのアクセスを許可してください。','Créez une présentation modifiable dans votre Drive. Au premier usage, autorisez l’accès aux fichiers créés par cette application ou sélectionnés par vous.','Cree una presentación editable en su Drive. La primera vez, autorice el acceso a los archivos que esta aplicación crea o que usted selecciona.','Создайте редактируемую презентацию в своём Диске. При первом использовании разрешите доступ к файлам, созданным приложением или выбранным вами.'],
  slidesSaved:['已儲存至你的 Drive；請檢查轉換後的版面。刪除此任務不會刪除 Google 簡報。','Saved to your Drive. Review the converted layout. Deleting this task will not delete the Google presentation.','Drive に保存しました。変換後のレイアウトを確認してください。このタスクを削除しても Google スライドは削除されません。','Enregistré dans votre Drive. Vérifiez la mise en page convertie. Supprimer cette tâche ne supprime pas la présentation Google.','Guardado en su Drive. Revise el diseño convertido. Eliminar esta tarea no elimina la presentación de Google.','Сохранено на вашем Диске. Проверьте оформление после преобразования. Удаление задачи не удалит Google Презентацию.'],
  slidesDownloads:['也可下載 PowerPoint；下方 PDF 為預覽。','You can also download PowerPoint. The PDF below is a preview.','PowerPoint もダウンロードできます。下の PDF はプレビューです。','Vous pouvez aussi télécharger le PowerPoint. Le PDF ci-dessous est un aperçu.','También puede descargar PowerPoint. El PDF de abajo es una vista previa.','Также можно скачать PowerPoint. PDF ниже служит для предпросмотра.'],
  slidesConsent:['尚未授權建立 Google 簡報。請重試並允許所需的檔案權限，或下載 PowerPoint。','Permission to create a Google presentation was not granted. Retry and allow file access, or download PowerPoint.','Google スライドを作成する権限がありません。再試行してファイルへのアクセスを許可するか、PowerPoint をダウンロードしてください。','Autorisation non accordée. Réessayez en autorisant l’accès aux fichiers, ou téléchargez le PowerPoint.','No se concedió permiso para crear la presentación. Reintente y permita el acceso a archivos, o descargue PowerPoint.','Разрешение на создание презентации не получено. Повторите и разрешите доступ к файлам либо скачайте PowerPoint.'],
  slidesPopup:['Google 授權視窗已關閉或遭到阻擋，請允許彈出視窗後重試。','The Google authorization window was closed or blocked. Allow popups and retry.','Google の認証ウィンドウが閉じられたかブロックされました。ポップアップを許可して再試行してください。','La fenêtre Google a été fermée ou bloquée. Autorisez les fenêtres contextuelles et réessayez.','La ventana de autorización se cerró o bloqueó. Permita ventanas emergentes y reintente.','Окно авторизации Google закрыто или заблокировано. Разрешите всплывающие окна и повторите.'],
  slidesAccount:['Google Drive 帳號與目前登入帳號不同。請切換為相同帳號後重試。','The Drive account differs from your signed-in account. Switch to the same account and retry.','Drive のアカウントがログイン中のアカウントと異なります。同じアカウントに切り替えて再試行してください。','Le compte Drive diffère du compte connecté. Utilisez le même compte et réessayez.','La cuenta de Drive no coincide con la sesión. Cambie a la misma cuenta y reintente.','Аккаунт Диска отличается от аккаунта входа. Переключитесь на тот же аккаунт и повторите.'],
  slidesTokenExpired:['Google 授權已逾時，請再次點擊按鈕完成授權。','Google authorization expired. Click the button again to authorize.','Google の認証が期限切れです。もう一度ボタンを押して認証してください。','L’autorisation Google a expiré. Cliquez à nouveau pour autoriser.','La autorización de Google caducó. Pulse de nuevo para autorizar.','Срок авторизации Google истёк. Нажмите кнопку ещё раз.'],
  slidesUnsupported:['此帳號目前無法將 PowerPoint 轉為 Google Slides，請先下載 PowerPoint。','This account cannot currently convert PowerPoint to Google Slides. Download PowerPoint instead.','このアカウントでは現在 PowerPoint を Google スライドに変換できません。PowerPoint をダウンロードしてください。','Ce compte ne peut pas convertir le PowerPoint en Google Slides actuellement. Téléchargez le PowerPoint.','Esta cuenta no puede convertir PowerPoint a Google Slides ahora. Descargue PowerPoint.','Этот аккаунт сейчас не может преобразовать PowerPoint в Google Презентацию. Скачайте PowerPoint.'],
  slidesUnavailable:['無法載入 Google 授權，請重試或下載 PowerPoint。','Google authorization could not load. Retry or download PowerPoint.','Google の認証を読み込めません。再試行するか PowerPoint をダウンロードしてください。','Impossible de charger l’autorisation Google. Réessayez ou téléchargez le PowerPoint.','No se pudo cargar la autorización de Google. Reintente o descargue PowerPoint.','Не удалось загрузить авторизацию Google. Повторите или скачайте PowerPoint.'],
  slidesFailed:['未能確認 Google Slides 儲存完成。請稍後重試，系統會先查找已建立的副本；也可先下載 PowerPoint。','Could not confirm the Google Slides save. Retry shortly; existing copies are checked first. You can also download PowerPoint.','Google スライドへの保存を確認できません。後でもう一度お試しください。既存のコピーを先に確認します。PowerPoint もダウンロードできます。','Enregistrement Google Slides non confirmé. Réessayez bientôt ; les copies existantes seront vérifiées d’abord. Vous pouvez aussi télécharger le PowerPoint.','No se pudo confirmar el guardado. Reintente en breve; primero se buscarán copias existentes. También puede descargar PowerPoint.','Не удалось подтвердить сохранение. Повторите позже: сначала проверяются существующие копии. Также можно скачать PowerPoint.'],
  createChart:['產出圖表','Create chart','図表を作成','Créer un graphique','Crear gráfico','Создать диаграмму'],
  artifactIntro:['以這則回答與其引用來源建立草稿，確認後產出檔案。','Create a draft from this answer and its cited sources, then review it before export.','この回答と引用元から下書きを作成し、確認後に出力します。','Créez un brouillon à partir de cette réponse et de ses sources, puis validez-le avant export.','Cree un borrador con esta respuesta y sus fuentes y revíselo antes de exportar.','Создайте черновик по этому ответу и его источникам, затем проверьте перед экспортом.'],
  answerSources:['自動使用此回答的 {count} 份引用來源。','Uses the {count} sources cited by this answer automatically.','この回答の引用元 {count} 件を自動で使用します。','Utilise automatiquement les {count} sources citées dans cette réponse.','Usa automáticamente las {count} fuentes citadas en esta respuesta.','Автоматически использует {count} источников этого ответа.'],
  targetLanguage:['產出語言','Output language','出力言語','Langue du résultat','Idioma del resultado','Язык результата'],
  audience:['受眾','Audience','対象読者','Public','Público','Аудитория'],
  defaultAudience:['研究與政策工作者','Researchers and policy practitioners','研究者・政策担当者','Chercheurs et responsables publics','Investigadores y responsables de políticas','Исследователи и специалисты по политике'],
  pages:['目標頁數','Target slide count','目標スライド数','Nombre de diapositives visé','Número de diapositivas','Число слайдов'],
  createDraft:['建立草稿','Create draft','下書きを作成','Créer le brouillon','Crear borrador','Создать черновик'],
  noSources:['這則回答尚無可用的原始來源。','This answer has no available original sources.','この回答には利用可能な原典がありません。','Cette réponse n’a pas de sources originales disponibles.','Esta respuesta no tiene fuentes originales disponibles.','У этого ответа нет доступных первоисточников.'],
  queued:['等待處理','Queued','待機中','En attente','En cola','В очереди'],
  running:['處理中','Processing','処理中','En cours','Procesando','Обработка'],
  render_queued:['等待產出','Waiting to render','出力待ち','En attente de rendu','Esperando renderizado','Ожидание экспорта'],
  awaiting_review:['等待確認草稿','Review draft','下書きを確認','Brouillon à vérifier','Revisar borrador','Проверка черновика'],
  completed:['已完成','Completed','完了','Terminé','Completado','Готово'],
  failed:['未完成','Failed','失敗','Échec','Error','Ошибка'],
  cancelled:['已取消','Cancelled','キャンセル済み','Annulé','Cancelado','Отменено'],
  preview:['產出預覽','Output preview','出力プレビュー','Aperçu du résultat','Vista previa','Предпросмотр результата'],
  progress:['任務進度','Task progress','タスクの進捗','Progression','Progreso','Ход выполнения'],
  indexWaiting:['索引約需 10～30 分鐘，完成前維持前一版本。可稍後從「我的產出」查看。','Indexing usually takes 10–30 minutes. The previous version stays active. Check My outputs later.','索引には通常 10～30 分かかります。完了までは前の版を使用します。「作成した資料」で確認できます。','L’indexation prend généralement 10 à 30 minutes. La version précédente reste active. Consultez Mes productions.','La indexación suele tardar 10–30 minutos. Se mantiene la versión anterior. Consulte Mis resultados.','Индексация обычно занимает 10–30 минут. Пока действует предыдущая версия. Проверьте «Мои результаты».'],
  indexDone:['已發布 v{version}，{count} 個切片通過搜尋驗證。','Published v{version}; {count} chunks verified in search.','v{version} を公開しました。{count} 件のチャンクを検索で検証済みです。','Version {version} publiée ; {count} segments vérifiés dans la recherche.','Publicada v{version}; {count} fragmentos verificados en la búsqueda.','Опубликована v{version}; {count} фрагментов проверено поиском.'],
  stale:['來源已更新，請重新建立這份產出。','Sources changed. Create this output again.','原典が更新されました。再作成してください。','Les sources ont changé. Recréez ce résultat.','Las fuentes cambiaron. Cree el resultado de nuevo.','Источники изменились. Создайте результат заново.'],
  reviewDraft:['檢查內容、引用與限制，確認後產出檔案。','Review the content, citations and limitations before exporting.','内容、引用、制約を確認してから出力してください。','Vérifiez le contenu, les citations et les limites avant export.','Revise contenido, citas y limitaciones antes de exportar.','Проверьте содержание, ссылки и ограничения перед экспортом.'],
  slidePlan:['目前預計 {count} 頁，含限制與來源。','Currently {count} slides, including limitations and sources.','現在の予定は {count} 枚です。制約と出典を含みます。','Prévision : {count} diapositives, limites et sources comprises.','Se prevén {count} diapositivas, incluidas limitaciones y fuentes.','Ожидается {count} слайдов, включая ограничения и источники.'],
  title:['標題','Title','タイトル','Titre','Título','Название'],
  summary:['摘要','Summary','要約','Résumé','Resumen','Краткое содержание'],
  sectionTitle:['段落標題','Section heading','節の見出し','Titre de section','Título de sección','Заголовок раздела'],
  sectionBody:['段落內容','Section content','節の内容','Contenu de section','Contenido de sección','Содержание раздела'],
  limitations:['限制','Limitations','制約','Limites','Limitaciones','Ограничения'],
  confirmOutput:['確認內容並產出','Confirm and export','確認して出力','Valider et exporter','Confirmar y exportar','Подтвердить и экспортировать'],
  translationNote:['AI 輔助譯文，請對照原文確認。','AI-assisted translation. Check it against the original.','AI による翻訳です。原文と照合してください。','Traduction assistée par IA. Vérifiez avec l’original.','Traducción asistida por IA. Compruébela con el original.','Перевод с помощью ИИ. Сверяйте с оригиналом.'],
  translationComplete:['選定段落翻譯完成。','Selected passages translated.','選択した段落の翻訳が完了しました。','Passages sélectionnés traduits.','Pasajes seleccionados traducidos.','Выбранные фрагменты переведены.'],
  translationPartial:['部分段落仍在翻譯中。','Some passages are still being translated.','一部の段落は翻訳中です。','Certains passages sont encore en cours de traduction.','Algunos pasajes aún se están traduciendo.','Некоторые фрагменты ещё переводятся.'],
  original:['原文','Original','原文','Original','Original','Оригинал'],
  chartPreview:['圖表預覽','Chart preview','図表プレビュー','Aperçu du graphique','Vista previa del gráfico','Предпросмотр диаграммы'],
  cancelTask:['取消任務','Cancel task','タスクをキャンセル','Annuler la tâche','Cancelar tarea','Отменить задачу'],
  deleteTask:['刪除任務與檔案','Delete task and files','タスクとファイルを削除','Supprimer la tâche et les fichiers','Eliminar tarea y archivos','Удалить задачу и файлы'],
  tasksIntro:['查看進度與下載產出，檔案保存 24 小時。','Check progress and download outputs. Files are kept for 24 hours.','進捗の確認とダウンロードができます。ファイルは 24 時間保存されます。','Suivez la progression et téléchargez les résultats. Conservation : 24 heures.','Consulte el progreso y descargue resultados. Los archivos se guardan 24 horas.','Проверяйте ход работы и скачивайте результаты. Файлы хранятся 24 часа.'],
  noTasks:['目前沒有任務。','No tasks yet.','タスクはありません。','Aucune tâche pour le moment.','Aún no hay tareas.','Задач пока нет.'],
  expires:['保存至 {date}','Available until {date}','保存期限：{date}','Disponible jusqu’au {date}','Disponible hasta {date}','Доступно до {date}'],
  readerTitle:['引用原文','Cited passages','引用された原文','Passages cités','Pasajes citados','Цитируемые фрагменты'],
  sourceLanguage:['原文語言','Original language','原文の言語','Langue originale','Idioma original','Язык оригинала'],
  version:['版本','Version','版','Version','Versión','Версия'],
  page:['頁碼','Page','ページ','Page','Página','Страница'],
  unknownPage:['未提供','Not provided','不明','Non indiquée','No disponible','Не указана'],
  openOriginal:['查看原始文件','Open original document','原本を開く','Ouvrir le document original','Abrir documento original','Открыть исходный документ'],
  translatePassage:['翻譯引用段落','Translate cited passages','引用部分を翻訳','Traduire les passages cités','Traducir pasajes citados','Перевести цитируемые фрагменты'],
  translateTarget:['翻譯語言','Translate into','翻訳先の言語','Traduire en','Traducir al','Перевести на'],
  citedCount:['顯示與這則引用對應的 {count} 個原文段落。','Showing {count} original passages for this citation.','この引用に対応する原文 {count} 段落を表示しています。','Affichage de {count} passages originaux correspondant à cette citation.','Se muestran {count} pasajes originales de esta cita.','Показано {count} исходных фрагментов для этой ссылки.'],
  noPassage:['無法精確對應原文段落，請開啟原始文件查看。','Could not locate the original passage precisely. Open the original document.','原文の位置を特定できません。原本を開いてください。','Impossible de localiser précisément le passage. Ouvrez le document original.','No se pudo localizar el pasaje exacto. Abra el documento original.','Не удалось точно найти фрагмент. Откройте исходный документ.'],
  sameLanguage:['原文已是所選語言。','The original is already in this language.','原文はすでに選択した言語です。','L’original est déjà dans cette langue.','El original ya está en este idioma.','Оригинал уже на выбранном языке.'],
  ocrBlocked:['這段所在頁面需要先完成文字辨識，暫時無法翻譯。','This passage needs text recognition before translation.','この箇所は翻訳前に文字認識が必要です。','Ce passage nécessite une reconnaissance de texte avant traduction.','Este pasaje requiere reconocimiento de texto antes de traducirlo.','Перед переводом этого фрагмента требуется распознавание текста.'],
  extractionNote:['這是原始文件的擷取文字，表格或圖片請回查原檔。','This is extracted text. Check tables and images in the original file.','抽出されたテキストです。表や画像は原本で確認してください。','Texte extrait : consultez le fichier original pour les tableaux et images.','Texto extraído: consulte tablas e imágenes en el archivo original.','Это извлечённый текст. Таблицы и изображения проверяйте в исходном файле.'],
  extractionAck:['已確認所顯示的原文段落可供翻譯。','I have checked that the displayed passages can be translated.','表示された原文が翻訳可能であることを確認しました。','J’ai vérifié que les passages affichés peuvent être traduits.','He comprobado que los pasajes mostrados pueden traducirse.','Я проверил, что показанные фрагменты пригодны для перевода.'],
  library:['來源文件庫','Source library','原典ライブラリ','Bibliothèque des sources','Biblioteca de fuentes','Библиотека источников'],
  adminTitle:['治理文件庫與切片狀態','Governance documents and chunks','ガバナンス資料とチャンク','Documents de gouvernance et segments','Documentos de gobernanza y fragmentos','Документы по управлению и фрагменты'],
  returnResearch:['返回研究介面','Back to research','調査画面に戻る','Retour à la recherche','Volver a la investigación','Вернуться к исследованию'],
  aiTools:['AI 標註工具','AI annotation tools','AI 注釈ツール','Outils d’annotation IA','Herramientas de anotación IA','Инструменты ИИ-разметки'],
  libraryIntro:['編輯切片後先儲存草稿、查看差異，再送出索引。原文與頁碼會保留。','Save chunk edits, review the changes, then submit for indexing. Originals and page references are preserved.','チャンクを保存し、差分を確認して索引に送信します。原文とページ情報は保持されます。','Enregistrez les segments, vérifiez les modifications puis lancez l’indexation. Les originaux et pages sont conservés.','Guarde los fragmentos, revise los cambios y envíe a indexar. Se conservan originales y páginas.','Сохраните фрагменты, проверьте изменения и отправьте на индексацию. Оригиналы и страницы сохраняются.'],
  newDocument:['新增文件','Add document','資料を追加','Ajouter un document','Añadir documento','Добавить документ'],
  originalFile:['原始文件','Original file','原本ファイル','Fichier original','Archivo original','Исходный файл'],
  detectLanguage:['原文語言（留空自動偵測）','Original language (auto-detect if empty)','原文の言語（空欄で自動検出）','Langue originale (détection si vide)','Idioma original (automático si vacío)','Язык оригинала (автоопределение, если пусто)'],
  cityMetadata:['文件城市（選填）','Document city (optional)','資料の都市（任意）','Ville du document (facultatif)','Ciudad del documento (opcional)','Город документа (необязательно)'],
  cleanedText:['清理後文字（選填，另存草稿）','Cleaned text (optional, saved as a draft)','修正済みテキスト（任意、下書き保存）','Texte nettoyé (facultatif, enregistré en brouillon)','Texto corregido (opcional, guardado como borrador)','Исправленный текст (необязательно, сохраняется как черновик)'],
  rights:['已確認可處理、翻譯並依設定分享此文件','I have permission to process, translate and share this document as configured','この資料を処理・翻訳し、設定に従って共有する権限があります','Je peux traiter, traduire et partager ce document selon les paramètres','Tengo permiso para procesar, traducir y compartir este documento según la configuración','У меня есть право обрабатывать, переводить и делиться документом согласно настройкам'],
  uploadDraft:['上傳並建立草稿','Upload and create draft','アップロードして下書き作成','Importer et créer un brouillon','Subir y crear borrador','Загрузить и создать черновик'],
  searchDocuments:['搜尋文件','Search documents','資料を検索','Rechercher des documents','Buscar documentos','Поиск документов'],
  refresh:['重新整理','Refresh','更新','Actualiser','Actualizar','Обновить'],
  noDocuments:['目前沒有可讀取的文件。','No readable documents yet.','閲覧可能な資料はありません。','Aucun document accessible.','No hay documentos accesibles.','Доступных документов пока нет.'],
  draftRevision:['草稿修訂 {revision}','Draft revision {revision}','下書き改訂 {revision}','Révision du brouillon {revision}','Revisión del borrador {revision}','Редакция черновика {revision}'],
  publishedVersion:['發布 v{version}','Published v{version}','公開版 v{version}','Version publiée {version}','Publicada v{version}','Опубликована v{version}'],
  editChunks:['編輯切片','Edit chunks','チャンクを編集','Modifier les segments','Editar fragmentos','Редактировать фрагменты'],
  historical:['既有治理文件（{count}）','Historical documents ({count})','既存資料（{count}）','Documents existants ({count})','Documentos existentes ({count})','Существующие документы ({count})'],
  historicalHint:['既有共用來源由管理員管理；編輯者可管理自己上傳的文件。','Administrators manage historical shared sources; editors manage their own uploads.','既存の共有資料は管理者が、アップロードした資料は各編集者が管理します。','Les administrateurs gèrent les sources partagées existantes ; les éditeurs gèrent leurs imports.','Los administradores gestionan fuentes compartidas existentes; los editores, sus archivos.','Администраторы управляют существующими общими источниками; редакторы — своими загрузками.'],
  openDraft:['建立／開啟草稿','Create / open draft','下書きを作成／開く','Créer / ouvrir le brouillon','Crear / abrir borrador','Создать / открыть черновик'],
  editor:['切片編輯器','Chunk editor','チャンクエディター','Éditeur de segments','Editor de fragmentos','Редактор фрагментов'],
  extracted:['原始擷取','Original extraction','原文の抽出結果','Texte original extrait','Texto original extraído','Извлечённый оригинал'],
  draftChunks:['切片草稿（{count}）','Draft chunks ({count})','下書きチャンク（{count}）','Segments du brouillon ({count})','Fragmentos del borrador ({count})','Фрагменты черновика ({count})'],
  chunkContent:['切片 {number} 內容','Chunk {number} content','チャンク {number} の内容','Contenu du segment {number}','Contenido del fragmento {number}','Содержание фрагмента {number}'],
  merge:['與下一片合併','Merge with next','次と結合','Fusionner avec le suivant','Combinar con el siguiente','Объединить со следующим'],
  split:['拆分為兩片','Split into two','2 つに分割','Diviser en deux','Dividir en dos','Разделить на два'],
  chunkSize:['自動切片字數上限','Maximum characters per chunk','チャンクの最大文字数','Nombre maximal de caractères par segment','Máximo de caracteres por fragmento','Максимум символов во фрагменте'],
  rechunk:['重新切片並儲存','Rechunk and save','再分割して保存','Redécouper et enregistrer','Dividir de nuevo y guardar','Разбить заново и сохранить'],
  resetPrompt:['這會以原始擷取文字取代目前草稿。已發布版本不變。','This replaces the draft with chunks from the original extraction. The published version stays unchanged.','原文から再分割して下書きを置き換えます。公開版は変わりません。','Le brouillon sera remplacé par des segments du texte original. La version publiée reste inchangée.','El borrador se reemplazará por fragmentos del original. La versión publicada no cambia.','Черновик заменится фрагментами исходного текста. Опубликованная версия не изменится.'],
  confirm:['確認','Confirm','確認','Confirmer','Confirmar','Подтвердить'],
  saveDraft:['儲存草稿','Save draft','下書きを保存','Enregistrer le brouillon','Guardar borrador','Сохранить черновик'],
  saved:['草稿已儲存，尚未更新索引。','Draft saved. The index has not changed yet.','下書きを保存しました。索引はまだ更新されていません。','Brouillon enregistré. L’index n’a pas encore changé.','Borrador guardado. El índice aún no ha cambiado.','Черновик сохранён. Индекс ещё не изменился.'],
  unsaved:['有尚未儲存的修改，請先儲存再查看差異。','Save your changes before reviewing the publication diff.','公開差分を確認する前に変更を保存してください。','Enregistrez les modifications avant de vérifier les différences.','Guarde los cambios antes de revisar las diferencias.','Сохраните изменения перед просмотром различий.'],
  leavePrompt:['要放棄尚未儲存的修改並返回嗎？','Discard unsaved changes and go back?','未保存の変更を破棄して戻りますか？','Abandonner les modifications et revenir ?','¿Descartar los cambios y volver?','Отменить несохранённые изменения и вернуться?'],
  viewDiff:['查看發布差異','Review publication changes','公開差分を確認','Vérifier les modifications','Revisar cambios de publicación','Просмотреть изменения публикации'],
  noChanges:['內容與目前發布版本相同。','Content matches the published version.','内容は公開版と同じです。','Contenu identique à la version publiée.','El contenido coincide con la versión publicada.','Содержание совпадает с опубликованной версией.'],
  share:['所有已登入使用者可讀取','Readable by all signed-in users','ログインした全ユーザーが閲覧可能','Accessible à tous les utilisateurs connectés','Visible para todos los usuarios conectados','Доступно всем вошедшим пользователям'],
  indexingDisabled:['索引發布尚未啟用，仍可儲存草稿。','Index publication is disabled. Drafts can still be saved.','索引の公開は無効です。下書きは保存できます。','Publication dans l’index désactivée. Les brouillons restent enregistrables.','La publicación del índice está desactivada. Puede guardar borradores.','Публикация в индекс отключена. Черновики можно сохранять.'],
  pendingHint:['已有索引工作進行中，可從「我的產出」查看進度。','Indexing is in progress. Check My outputs for updates.','索引作成中です。「作成した資料」で進捗を確認できます。','Indexation en cours. Consultez Mes productions.','Indexación en curso. Consulte Mis resultados.','Идёт индексация. Следите в разделе «Мои результаты».'],
  publish:['確認差異並送出索引','Confirm changes and index','差分を確認して索引に送信','Valider et indexer','Confirmar cambios e indexar','Подтвердить и индексировать'],
  rollback:['回復前一發布版本','Restore previous publication','前の公開版に戻す','Restaurer la publication précédente','Restaurar publicación anterior','Восстановить предыдущую публикацию'],
  checkIndex:['核對實際索引內容','Verify indexed content','索引内容を検証','Vérifier le contenu indexé','Verificar contenido indexado','Проверить содержимое индекса'],
  verified:['實際索引 v{version}：符合發布內容','Index v{version}: matches publication','索引 v{version}：公開内容と一致','Index v{version} : conforme à la publication','Índice v{version}: coincide con la publicación','Индекс v{version}: соответствует публикации'],
  notVerified:['實際索引 v{version}：尚未符合發布內容','Index v{version}: not yet matching','索引 v{version}：まだ一致していません','Index v{version} : pas encore conforme','Índice v{version}: aún no coincide','Индекс v{version}: пока не соответствует'],
  unpublished:['尚未發布','Unpublished','未公開','Non publié','Sin publicar','Не опубликовано'],
  'legacy-index':['既有來源索引','Historical source index','既存原典の索引','Index des sources existantes','Índice de fuentes existentes','Индекс существующих источников'],
  pending:['等待索引','Index pending','索引待ち','Indexation en attente','Índice pendiente','Ожидание индексации'],
  indexed:['索引完成','Indexed','索引作成済み','Indexé','Indexado','Проиндексировано'],
  indexed_cleanup_pending:['新版已生效，舊索引清理中','Published; old index cleanup pending','公開済み・旧索引を整理中','Publié ; nettoyage de l’ancien index en attente','Publicado; limpieza del índice anterior pendiente','Опубликовано; ожидается очистка старого индекса'],
  mcpIntro:['建立一小時有效的個人 MCP 憑證，權限與目前帳號相同。請勿分享；新憑證會撤銷上一個。','Create a one-hour personal MCP token with your current permissions. Do not share it. A new token revokes the previous one.','現在の権限で 1 時間有効な個人 MCP トークンを作成します。共有しないでください。新規作成で前のトークンは無効になります。','Créez un jeton MCP personnel valable une heure avec vos droits actuels. Ne le partagez pas. Un nouveau jeton révoque le précédent.','Cree un token MCP personal de una hora con sus permisos actuales. No lo comparta. Un token nuevo revoca el anterior.','Создайте личный MCP-токен на час с текущими правами. Не передавайте его другим. Новый токен отменяет предыдущий.'],
  createToken:['建立短期憑證','Create temporary token','一時トークンを作成','Créer un jeton temporaire','Crear token temporal','Создать временный токен'],
  copyToken:['複製憑證','Copy token','トークンをコピー','Copier le jeton','Copiar token','Копировать токен'],
  copied:['已複製','Copied','コピー済み','Copié','Copiado','Скопировано'],
  revokeToken:['撤銷我的 MCP 憑證','Revoke my MCP token','MCP トークンを無効化','Révoquer mon jeton MCP','Revocar mi token MCP','Отозвать мой MCP-токен'],
  tokenExpiry:['有效至 {date}。關閉後不保存明文。','Valid until {date}. The token is not kept after closing.','有効期限：{date}。閉じると平文は保存されません。','Valable jusqu’au {date}. Le jeton n’est pas conservé après fermeture.','Válido hasta {date}. El token no se guarda al cerrar.','Действует до {date}. После закрытия токен не сохраняется.'],
} as const satisfies Record<string, readonly [string,string,string,string,string,string]>;
export type PanelKey = keyof typeof PANEL_COPY;
const indexes:Record<InterfaceLanguage,number>={zh:0,en:1,ja:2,fr:3,es:4,ru:5};
export function panelText(lang:InterfaceLanguage, key:PanelKey, params:Record<string,string|number>={}) {
  return PANEL_COPY[key][indexes[lang]].replace(/\{(\w+)\}/g,(_,name)=>String(params[name]??`{${name}}`));
}
export function panelError(error:unknown):PanelKey {
  if (/Slide text exceeds readable layout|readable slide area|Shorten chart category/.test(String((error as Error)?.message||''))) return 'slideTextTooLong';
  const status=(error as {status?:number})?.status;
  return ({401:'expired',403:'denied',404:'missing',409:'conflict',413:'tooLarge',415:'invalid',422:'invalid',429:'rateLimit',503:'unavailable'} as Record<number,PanelKey>)[status!] || 'error';
}
