import {InterfaceLanguage} from './languages';

const zh = {
  scope: '1 · 研究範圍', city: '想研究哪個城市？', cityPlaceholder: '例如：台北', cityHint: '留空就搜尋所有城市。',
  languages: '原始文件的語言', allLanguages: '不限語言', languageHint: '只影響「讀哪些原文」，不影響回答的語言。',
  make: '2 · 把回答變成成果', chart: '一張圖表', chartHint: '數字都對應原文', report: '一份報告 PDF', reportHint: '含引用與限制說明',
  slides: '一組投影片', slidesHint: '可在 PowerPoint 編輯', makeHint: '取得有來源的回答後，就能建立成果。',
  library: '文件庫 · 看所有原始文件', tasks: '我的產出 · 進行中與下載', mcp: '連到其他 AI 工具（MCP）',
  samples: '可以這樣問', steps: ['提問。需要時在左邊指定城市。', '看回答，右邊會列出用到的文件。', '要交件時，轉成圖表、報告或投影片。'],
  sourceTitle: '回答用到的文件', sourceEmpty: '回答出現後，這裡會列出它讀過的原始文件。點一份就能看原文段落與翻譯。',
  sourceHint: '請回查原文確認內容。若找不到需要的資料，可以換個問法或調整研究範圍。', read: '看原文與翻譯',
  scopeToggle: '研究範圍與工具', sourceToggle: '查看來源', languageLabel: '介面語言', send: '送出', copyError: '複製失敗，請選取回答後自行複製。', page: '頁',
};
type ResearchCopy = typeof zh;
const en: ResearchCopy = {
  scope: '1 · Research scope', city: 'Which city are you researching?', cityPlaceholder: 'For example: Taipei', cityHint: 'Leave blank to search all cities.',
  languages: 'Languages of original documents', allLanguages: 'Any language', languageHint: 'Controls which sources are read, not the language of the answer.',
  make: '2 · Turn answers into work', chart: 'A chart', chartHint: 'Figures linked to their sources', report: 'A PDF report', reportHint: 'With citations and limitations',
  slides: 'A slide deck', slidesHint: 'Editable in PowerPoint', makeHint: 'Get an answer with sources to create an output.',
  library: 'Library · Original documents', tasks: 'My outputs · Progress & downloads', mcp: 'Connect other AI tools (MCP)',
  samples: 'Try asking', steps: ['Ask a question. Set a city on the left if needed.', 'Read the answer and its sources on the right.', 'Turn your research into a chart, report, or slides.'],
  sourceTitle: 'Sources for this answer', sourceEmpty: 'Original documents will appear here with the answer. Select one to read passages and translations.',
  sourceHint: 'Check the originals to verify the answer. Refine your question or research scope if needed.', read: 'Read original & translate',
  scopeToggle: 'Research scope & tools', sourceToggle: 'View sources', languageLabel: 'Interface language', send: 'Send', copyError: 'Could not copy. Select the answer and copy it manually.', page: 'p.',
};
const translations: Record<Exclude<InterfaceLanguage, 'zh' | 'en'>, ResearchCopy> = {
  ja: {...en, scope:'1 · 調査範囲', city:'どの都市を調べますか？', cityPlaceholder:'例：台北', cityHint:'空欄ならすべての都市を検索します。', languages:'原典の言語', allLanguages:'すべての言語', languageHint:'検索する原典の言語を指定します。回答の言語には影響しません。', make:'2 · 回答から成果物へ', chart:'図表', chartHint:'数値と原典を対応', report:'PDF レポート', reportHint:'引用と制約を記載', slides:'スライド', slidesHint:'PowerPoint で編集可能', makeHint:'出典付きの回答を得ると作成できます。', library:'資料一覧 · 原典を読む', tasks:'作成した資料 · 進捗とダウンロード', mcp:'他の AI ツールに接続（MCP）', samples:'質問の例', steps:['質問します。必要なら左側で都市を指定。','回答と右側の原典を確認。','図表、レポート、スライドにまとめます。'], sourceTitle:'回答に使われた原典', sourceEmpty:'回答とともに原典が表示されます。選択すると原文と翻訳を読めます。', sourceHint:'原文で内容を確認してください。必要に応じて質問や範囲を変更できます。', read:'原文と翻訳を読む', scopeToggle:'調査範囲とツール', sourceToggle:'原典を表示', languageLabel:'表示言語', send:'送信', copyError:'コピーできませんでした。回答を選択してコピーしてください。', page:'ページ'},
  fr: {...en, scope:'1 · Périmètre de recherche', city:'Quelle ville étudiez-vous ?', cityPlaceholder:'Par exemple : Taipei', cityHint:'Laissez vide pour toutes les villes.', languages:'Langues des documents originaux', allLanguages:'Toutes les langues', languageHint:'Définit les sources consultées, pas la langue de la réponse.', make:'2 · Créer à partir des réponses', chart:'Un graphique', chartHint:'Chiffres reliés aux sources', report:'Un rapport PDF', reportHint:'Avec citations et limites', slides:'Une présentation', slidesHint:'Modifiable dans PowerPoint', makeHint:'Obtenez une réponse avec des sources pour créer un document.', library:'Documents · Sources originales', tasks:'Mes productions · Suivi et téléchargements', mcp:'Connecter d’autres outils IA (MCP)', samples:'Exemples de questions', steps:['Posez une question. Précisez une ville à gauche.','Lisez la réponse et les sources à droite.','Créez un graphique, un rapport ou une présentation.'], sourceTitle:'Sources de cette réponse', sourceEmpty:'Les sources apparaîtront avec la réponse. Sélectionnez un document pour lire et traduire les passages.', sourceHint:'Vérifiez le contenu dans les originaux. Affinez votre question ou votre recherche si nécessaire.', read:'Lire et traduire l’original', scopeToggle:'Périmètre et outils', sourceToggle:'Voir les sources', languageLabel:'Langue de l’interface', send:'Envoyer', copyError:'Échec de la copie. Sélectionnez et copiez le texte.', page:'p.'},
  es: {...en, scope:'1 · Alcance de investigación', city:'¿Qué ciudad investiga?', cityPlaceholder:'Por ejemplo: Taipéi', cityHint:'Déjelo vacío para buscar todas las ciudades.', languages:'Idiomas de los documentos originales', allLanguages:'Cualquier idioma', languageHint:'Define las fuentes consultadas, no el idioma de la respuesta.', make:'2 · Crear a partir de respuestas', chart:'Un gráfico', chartHint:'Cifras vinculadas a fuentes', report:'Un informe PDF', reportHint:'Con citas y limitaciones', slides:'Una presentación', slidesHint:'Editable en PowerPoint', makeHint:'Obtenga una respuesta con fuentes para crear un documento.', library:'Biblioteca · Documentos originales', tasks:'Mis resultados · Progreso y descargas', mcp:'Conectar otras herramientas de IA (MCP)', samples:'Puede preguntar', steps:['Haga una pregunta. Indique una ciudad a la izquierda.','Lea la respuesta y las fuentes a la derecha.','Cree un gráfico, informe o presentación.'], sourceTitle:'Fuentes de esta respuesta', sourceEmpty:'Los documentos aparecerán aquí con la respuesta. Seleccione uno para leer y traducir pasajes.', sourceHint:'Verifique el contenido en los originales. Ajuste la pregunta o el alcance si es necesario.', read:'Leer original y traducir', scopeToggle:'Alcance y herramientas', sourceToggle:'Ver fuentes', languageLabel:'Idioma de la interfaz', send:'Enviar', copyError:'No se pudo copiar. Seleccione y copie el texto.', page:'p.'},
  ru: {...en, scope:'1 · Область исследования', city:'Какой город вы изучаете?', cityPlaceholder:'Например: Тайбэй', cityHint:'Оставьте пустым для поиска по всем городам.', languages:'Языки оригинальных документов', allLanguages:'Любой язык', languageHint:'Определяет язык источников, а не ответа.', make:'2 · Создать по ответам', chart:'Диаграмма', chartHint:'Цифры со ссылками на источники', report:'Отчёт PDF', reportHint:'С цитатами и ограничениями', slides:'Презентация', slidesHint:'Редактируется в PowerPoint', makeHint:'Получите ответ с источниками, чтобы создать документ.', library:'Библиотека · Оригиналы', tasks:'Мои результаты · Статус и загрузки', mcp:'Подключить другие ИИ-инструменты (MCP)', samples:'Примеры вопросов', steps:['Задайте вопрос. При необходимости укажите город слева.','Прочитайте ответ и источники справа.','Создайте диаграмму, отчёт или презентацию.'], sourceTitle:'Источники этого ответа', sourceEmpty:'Здесь появятся источники ответа. Выберите документ для чтения и перевода.', sourceHint:'Проверяйте содержание по оригиналам. При необходимости уточните вопрос или область поиска.', read:'Читать оригинал и перевод', scopeToggle:'Область поиска и инструменты', sourceToggle:'Показать источники', languageLabel:'Язык интерфейса', send:'Отправить', copyError:'Не удалось скопировать. Выделите и скопируйте текст.', page:'стр.'},
};
export function researchCopy(lang: InterfaceLanguage): ResearchCopy {return lang === 'zh' ? zh : lang === 'en' ? en : translations[lang];}
